Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-application-bucket

  MyElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: my-application

  MyElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: !Ref MyElasticBeanstalkApplication
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.11.4 running Python 3.6

  MyEKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: my-eks-cluster
      RoleArn: !GetAtt MyEKSClusterRole.Arn
      Version: '1.20'
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-abcde012
          - subnet-bcde012a
          - subnet-fghi345a
        SecurityGroupIds:
          - sg-abcde012

  Resources:
  MyCustomResource:
    Type: 'Custom::MyCustomResource'
    Properties:
      ServiceToken: arn:aws:lambda:us-west-2:123456789012:function:my-function