name: Traveling_Salesman

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        run: |
          cd Python_Tests
          A_Test.py
          Annealing_Test.py
          Convex_Test.py
          QGA_Test.py

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install JavaScript dependencies
        run: |
          cd Application_Folder
          npm install

      - name: Run JavaScript tests
        run: |
          # Add commands to run your JavaScript tests here.

      - name: Build application
        run: |
          

      - name: Deploy application
        if: github.ref == 'refs/heads/main'  # Example condition, customize as needed
        run: |
          # Add commands to deploy your application here.
