name: Update Dependencies

on:
  push:
    branches:
      - master

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install and update Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --upgrade

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install and update JavaScript dependencies
      run: |
        npm install
        npm update
